# Generated by Django 4.1.7 on 2023-03-27 20:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=400)),
                ('last_name', models.CharField(max_length=400)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True, default='0000-00-0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('isbn', models.CharField(max_length=13)),
                ('description', models.CharField(max_length=400)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('FINANCE', 'FIN'), ('POLITICS', 'POL'), ('POWER', 'POW'), ('COMEDY', 'COM')], default='FIC', max_length=10)),
                ('language', models.CharField(choices=[('YORUBA', 'YOR'), ('IGBO', 'IGB'), ('HAUSA', 'HAU'), ('ENGLISH', 'ENG')], default='ENG', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='book.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('uniqueId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'A'), ('BORROWED', 'B')], default='A', max_length=10)),
                ('imprint', models.CharField(max_length=400)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
